#!/bin/sh
# Rebuilds nixos with modified config, does version management, saves logs

REBUILD_MODE="${1:-switch}"
CONFIG_DIR="${CONFIG_DIR:-$HOME/nixconfig}"
EDIT_FLAG=false
COMMIT_FLAG=false

for arg in "$@"; do
    if [ "$arg" = "--edit" ]; then
        EDIT_FLAG=true
        continue
    fi

    if [ "$arg" = "--commit" ]; then
        COMMIT_FLAG=true
        continue
    fi
done

git_wip () {
    git add --all
    git commit --allow-empty --message "WIP"
}

git_wip_revert () {
    git reset --soft HEAD~1
}

git_commit_generation () {
    gen=$(
        nixos-rebuild list-generations |
        grep current |
        awk -f util/parse-generations.awk
    )

    message="Generation $gen"

    git commit --amend --message "$message"
    if [ "$EDIT_FLAG" = true ]; then
        git commit --amend --edit
    fi
}

pushd "$CONFIG_DIR"

# Print changes to doublecheck
git diff -U0

git_wip

echo "Rebuilding NixOS configuration..."
sudo nixos-rebuild "$REBUILD_MODE" --flake . --show-trace &> nixos-switch.log ||
    (cat nixos-switch.log | grep --color error && false)

if [ $? -ne 0 ]; then
    echo "Rebuild failed"
    git_wip_revert
    exit 1
fi

if [ "$COMMIT_FLAG" = false ]; then
    git_wip_revert
else
    git_commit_generation
fi

git status --short --branch --renames --ahead-behind

popd # ~/nixconfig/
